=== gasparfalvip/WUWIOS_XMLGyak/XMLTaskWuwios/XMLSchemaWUWIOS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="videoteka" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string" />
                            <xs:element name="cim">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="iranyitosz" type="iranyitoszType" />
                                        <xs:element name="varos" type="xs:string" />
                                        <xs:element name="utcahsz" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="tk_id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="dolgozo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string" />
                            <xs:element name="beosztas" type="beosztasType" />
                            <xs:element name="ber" type="xs:positiveInteger" />
                        </xs:sequence>
                        <xs:attribute name="d_id" type="xs:integer" use="required" />
                        <xs:attribute name="tk_id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="tetel" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cim" type="xs:string" />
                            <xs:element name="tipus" type="tipusType" />
                            <xs:element name="megjelenes" type="datumType" />
                            <xs:element name="ar" type="xs:positiveInteger" />
                            <xs:element name="korhatar" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="t_id" type="xs:integer" use="required" />
                        <xs:attribute name="tk_id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="kuncsaft" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string" />
                            <xs:element name="szuld" type="datumType" />
                            <xs:element name="lakcim">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="iranyitosz" type="iranyitoszType" />
                                        <xs:element name="varos" type="xs:string" />
                                        <xs:element name="utcahsz" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="k_id" type="xs:integer" use="required" />
                        <xs:attribute name="tk_id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="kolcsonzes" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tétlek">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="t" minOccurs="1" maxOccurs="unbounded" type="kolcsonzesType" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="kk_id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="k_kk" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="idopont" type="datumType" />
                        </xs:sequence>
                        <xs:attribute name="k_id" type="xs:integer" use="required" />
                        <xs:attribute name="kk_id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>

        <xs:key name="videoteka_key">
            <xs:selector xpath="videoteka"/>
            <xs:field xpath="@tk_id"/>
        </xs:key>
        <xs:key name="dolgozo_key">
            <xs:selector xpath="dolgozo"/>
            <xs:field xpath="@d_id"/>
        </xs:key>
        <xs:key name="tetel_key">
            <xs:selector xpath="tetel"/>
            <xs:field xpath="@t_id"/>
        </xs:key>
        <xs:key name="kuncsaft_key">
            <xs:selector xpath="kuncsaft"/>
            <xs:field xpath="@k_id"/>
        </xs:key>
        <xs:key name="kolcsonzes_key">
            <xs:selector xpath="kolcsonzes"/>
            <xs:field xpath="@kk_id"/>
        </xs:key>

        <xs:keyref name="Fkey_dolgozo_tk" refer="videoteka_key">
            <xs:selector xpath="dolgozo"/>
            <xs:field xpath="@tk_id"/>
        </xs:keyref>

        <xs:keyref name="Fkey_tetel_tk" refer="videoteka_key">
            <xs:selector xpath="tetel"/>
            <xs:field xpath="@tk_id"/>
        </xs:keyref>

        <xs:keyref name="Fkey_kuncsaft_tk" refer="videoteka_key">
            <xs:selector xpath="kuncsaft"/>
            <xs:field xpath="@tk_id"/>
        </xs:keyref>

        <xs:keyref name="Fkey_kapcs_kuncsaft" refer="kuncsaft_key">
            <xs:selector xpath="k_kk"/>
            <xs:field xpath="@k_id"/>
        </xs:keyref>

        <xs:keyref name="Fkey_kapcs_kolcsonzes" refer="kolcsonzes_key">
            <xs:selector xpath="k_kk"/>
            <xs:field xpath="@kk_id"/>
        </xs:keyref>

    </xs:element>

    <xs:simpleType name="datumType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}[.]\d{2}[.]\d{2}[.]" />
            <xs:length value="11"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="iranyitoszType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4}" />
            <xs:length value="4"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="beosztasType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="vezető"/>
            <xs:enumeration value="eladó"/>
            <xs:enumeration value="ideiglenes"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DVD"/>
            <xs:enumeration value="Kazetta"/>
            <xs:enumeration value="Újság"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="kolcsonzesType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="5"/>
            <xs:enumeration value="6"/>
            <xs:enumeration value="7"/>
        </xs:restriction>
    </xs:simpleType>
    


</xs:schema>

=== gasparfalvip/WUWIOS_XMLGyak/XMLTaskWuwios2/XMLWUWIOS.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="XMLSchemaWUWIOS.xsd">

<!-- videótéka létrehozása -->
    <videoteka tk_id = "1">
        <nev>Menő TK</nev>        
        <cim>
            <iranyitosz>3535</iranyitosz>
            <varos>Miskolc</varos>
            <utcahsz>Eper 2.</utcahsz>
        </cim>
    </videoteka>

    <tulajdonos tk_id="1">
        <nev>Kerekes Kálmán</nev>
        <adoszam>123</adoszam>
    </tulajdonos>

<!-- a dolgozók létrehozása -->
    <dolgozo d_id = "1" tk_id="1">
        <nev>Cserepes Virág</nev>
        <beosztas>vezető</beosztas>
        <ber>240000</ber>
    </dolgozo>

    <dolgozo d_id = "2" tk_id="1">
        <nev>Ebéd Elek</nev>
        <beosztas>eladó</beosztas>
        <ber>180000</ber>
    </dolgozo>

    <dolgozo d_id = "3" tk_id="1">
        <nev>Rönk Ödön</nev>
        <beosztas>eladó</beosztas>
        <ber>190000</ber>
    </dolgozo>

<!-- a tételek létrehozása -->

    <tetel t_id = "1" tk_id = "1">
        <cim>Halálos iramban</cim>
        <tipus>Kazetta</tipus>
        <megjelenes>2001.06.22.</megjelenes>
        <ar>1000</ar>
        <korhatar>16</korhatar>
    </tetel>

    <tetel t_id = "2" tk_id = "1">
        <cim>Halálosabb iramban</cim>
        <tipus>Kazetta</tipus>
        <megjelenes>2003.06.06.</megjelenes>
        <ar>1200</ar>
        <korhatar>12</korhatar>
    </tetel>

    <tetel t_id = "3" tk_id = "1">
        <cim>Halálos iramban: Tokiói hajsza</cim>
        <tipus>DVD</tipus>
        <megjelenes>2006.06.04.</megjelenes>
        <ar>1400</ar>
        <korhatar>12</korhatar>
    </tetel>

    <tetel t_id = "4" tk_id = "1">
        <cim>Halálos iram</cim>
        <tipus>DVD</tipus>
        <megjelenes>2009.04.03.</megjelenes>
        <ar>1400</ar>
        <korhatar>16</korhatar>
    </tetel>

    <tetel t_id = "5" tk_id = "1">
        <cim>Halálos iram: Ötödik sebesség</cim>
        <tipus>DVD</tipus>
        <megjelenes>2011.04.29.</megjelenes>
        <ar>1600</ar>
        <korhatar>16</korhatar>
    </tetel>

    <tetel t_id = "6" tk_id = "1">
        <cim>Halálos iramban 6</cim>
        <tipus>DVD</tipus>
        <megjelenes>2013.05.24.</megjelenes>
        <ar>1600</ar>
        <korhatar>16</korhatar>
    </tetel>

    <tetel t_id = "7" tk_id = "1">
        <cim>Halálos iramban 7</cim>
        <tipus>DVD</tipus>
        <megjelenes>2015.04.03.</megjelenes>
        <ar>1600</ar>
        <korhatar>16</korhatar>
    </tetel>

<!-- a kuncsaftok létrehozása -->

    <kuncsaft k_id = "1" tk_id = "1">
        <nev>Nagy Endre</nev>
        <szuld>1987.01.07.</szuld>
        <lakcim>
            <iranyitosz>3535</iranyitosz>
            <varos>Miskolc</varos>
            <utcahsz>Béke utca 2.</utcahsz>
        </lakcim>
    </kuncsaft>

    <kuncsaft k_id = "2" tk_id = "1">
        <nev>Kiss Virág</nev>
        <szuld>2004.05.07.</szuld>
        <lakcim>
            <iranyitosz>3535</iranyitosz>
            <varos>Miskolc</varos>
            <utcahsz>Békés utca 8.</utcahsz>
        </lakcim>
    </kuncsaft>

    <kuncsaft k_id = "3" tk_id = "1">
        <nev>Közepes Kálmán</nev>
        <szuld>2000.05.09.</szuld>
        <lakcim>
            <iranyitosz>3535</iranyitosz>
            <varos>Miskolc</varos>
            <utcahsz>Békétlen utca 10.</utcahsz>
        </lakcim>
    </kuncsaft>

<!-- a kölcsönzések létrehozása -->
    <kolcsonzes kk_id = "1">
         <tétlek>
            <t>1</t>
         </tétlek>
    </kolcsonzes>

    <kolcsonzes kk_id = "2">
         <tétlek>
            <t>2</t>
         </tétlek>
    </kolcsonzes>

    <kolcsonzes kk_id = "3">
         <tétlek>
            <t>5</t>
            <t>6</t>
         </tétlek>
    </kolcsonzes>

<!-- a kuncsaft kölcsönzések kapcsoló tábla létrehozása -->

    <k_kk k_id= "1" kk_id = "1">
        <idopont>2022.05.06.</idopont>
    </k_kk>

    <k_kk k_id= "2" kk_id = "1">
        <idopont>2022.05.06.</idopont>
    </k_kk>

    <k_kk k_id= "3" kk_id = "2">
        <idopont>2022.07.20.</idopont>
    </k_kk>

    <k_kk k_id= "2" kk_id = "3">
        <idopont>2022.03.10.</idopont>
    </k_kk>


</root>
